apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-history.uiServiceName" . }}
  labels:
    {{- include "argo-history.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "argo-history.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-history.webhookServiceName" . }}
  labels:
    {{- include "argo-history.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "argo-history.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.servicePort }}
      targetPort: webhook
