{{- if not .Values.certManager.enabled }}
{{- $tlsData := include "argo-history.webhookTlsData" . | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-history.webhookSecretName" . }}
  labels:
    {{- include "argo-history.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ index $tlsData "tls.crt" }}
  tls.key: {{ index $tlsData "tls.key" }}
  ca.crt: {{ index $tlsData "ca.crt" }}
{{- end }}
